import 'list_of_data.dart';

List<List> mixFaithQuestions =[
  questionsOne,
  questionsTwo,
  questionsThree,
  questionsFour,
  questionsFive,
  questionsSix,
  questionsSeven,
  questionsEight,
  questionsNine,
  questionsTen,
  questionsEleven,
  questionsTwelve,
  questionsThirteen,
  questionsFourteen,
  questionsFifteen,
  questionsSixteen,
  questionsSeventeen,
  questionsEighteen,
  questionsNineteen,
  questionsTwenty,
  questionsTwentyOne,
  questionsTwentyTwo,
  questionsTwentyThree,
  questionsTwentyFour,
  questionsTwentyFive,
  questionsTwentySix,
  questionsTwentySeven,

];

List<String> namesOfTheLecturesOfFaith = [
  'لماذا ندرس العقيده',
  'توحيد الربوبية',
  ' مناقشة الملحدين',
  'أعبد ربنا صح',
  'انواع العبادات',
  'حول القبور والتوسل',
  'التوسل الممنوع',
  'انواع الشرك',
  'السحر والتنجيم',
  'الإيمان الصحيح',
  'تصحيح الايمان',
  'الرد علي اهل البدع',
  'الملائكة عالم يحبنا ونحبه',
  'الإيمان بالكتب',
  'الإيمان بالرسل',
  'حقوق النبي علي الامة',
  'الإسراء والمعراج',
  'أشراط الساعة الصغري',
  'أشراط الساعة الكبري',
  'نعيم القبر وعذابه\n(حقيقة ام خيال)',
  'مشاهد يوم القيامة',
  'هل الإنسان مخير أم ميسر',
  'مواجهة فكر داعش بفهم قضايا التكفير',
  'مواجهة فكر داعش بفهم قضايا التكفير2',
  'الولاء والبراء',
  'عقيدتنا في الصحابة',
  'عقائد الشيعه من كتبهم وأقوالهم',
];